E2Helper.Descriptions["stargateJumperSetInitialise"]="Initialise the Puddle Jumper as if a player just entered it. 1: Initialise, 0: Deinitialise. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetShield"]="Activate or deactivate the Puddle Jumper's shield. 1: Activate, 0: Deactivate. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetCloak"]="Activate or deactivate the Puddle Jumper's cloak. 1: Activate, 0: Deactivate. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetWeaponPods"]="Extend or retract the Puddle Jumper's weapon pods. 1: Extend, 0: Retract. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetEnginePods"]="Extend or retract the Puddle Jumper's engine pods. 1: Extend, 0: Retract. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetBulkhead"]="Open or close the Puddle Jumper's bulkhead door. 1: Open, 0: Close. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetDoor"]="Open or close the Puddle Jumper's compartment door. 1: Open, 0: Close. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetLight"]="Activate or deactivate the Puddle Jumper's front-facing lights. 1: Activate, 0: Deactivate. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetAutopilot"]="Activate or deactivate the Puddle Jumper's autopilot. 1: Activate, 0: Deactivate. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetStandby"]="Activate or deactivate the Puddle Jumper's engine standby. 1: Activate, 0: Deactivate. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetTarget"]="Set the target position for the Puddle Jumper's weapons. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperSetRoll"]="Set the Puddle Jumper's rotation from 0 to 359 degrees. Returns 1 if successful, 0 otherwise."

E2Helper.Descriptions["stargateJumperGetInitialise"]="Returns 1 if the Puddle Jumper is initialised, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetShield"]="Returns 1 if the Puddle Jumper's shield is activated, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetShieldStrength"]="Returns the Puddle Jumper's shield strength."
E2Helper.Descriptions["stargateJumperGetCloak"]="Returns 1 if the Puddle Jumper's cloak is activated, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetWeaponPods"]="Returns 1 if the Puddle Jumper's weapon pods are extended, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetEnginePods"]="Returns 1 if the Puddle Jumper's engine pods are extended, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetBulkhead"]="Returns 1 if the Puddle Jumper's bulkhead door is open, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetDoor"]="Returns 1 if the Puddle Jumper's compartment door is open, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetLight"]="Returns 1 if the Puddle Jumper's front-facing lights are activated, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetAutopilot"]="Returns 1 if the Puddle Jumper's autopilot is activated, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetStandby"]="Returns 1 if the Puddle Jumper's engine standby is activated, 0 otherwise."
E2Helper.Descriptions["stargateJumperGetTarget"]="Returns the target position for the Puddle Jumper's weapons."
E2Helper.Descriptions["stargateJumperGetFiredDrones"]="Returns an array containing 6 numbers, each representing if a specific drone has been fired."
E2Helper.Descriptions["stargateJumperGetRoll"]="Returns the Puddle Jumper's rotation from 0 to 359 degrees."
E2Helper.Descriptions["stargateJumperGetHealth"]="Returns the Puddle Jumper's health."
E2Helper.Descriptions["stargateJumperGetDriver"]="Returns the player driving the Puddle Jumper."
E2Helper.Descriptions["stargateJumperGetStargate"]="Returns the closest Stargate to the Puddle Jumper (the same one that would be dialed if you were using the built-in DHD)."

E2Helper.Descriptions["stargateJumperGetShieldOperational"]="Returns 1 if the Puddle Jumper's shield is operational (not destroyed), 0 if they aren't."
E2Helper.Descriptions["stargateJumperGetCloakOperational"]="Returns 1 if the Puddle Jumper's cloak operational (not destroyed), 0 if they aren't."
E2Helper.Descriptions["stargateJumperGetWeaponsOperational"]="Returns 1 if the Puddle Jumper's weapons are operational (not destroyed), 0 if they aren't."
E2Helper.Descriptions["stargateJumperGetEngineOperational"]="Returns 1 if the Puddle Jumper's engine is operational (not destroyed), 0 if they aren't."

E2Helper.Descriptions["stargateJumperSelfDestruct"]="Self destructs the Puddle Jumper. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperExitDriver"]="Forces the current driver to leave the Puddle Jumper. Returns 1 if successful, 0 otherwise."
E2Helper.Descriptions["stargateJumperFireDrone"]="Fires a drone from the Puddle Jumper's weapon pods. Returns 1 if successful, 0 otherwise. You must wait 0.5 seconds before firing another drone."

E2Helper.Descriptions["stargateJumperMove"]="Moves the Puddle Jumper to the specified position, relative to itself. Returns 1 if successful, 0 otherwise."